# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Plant.create(name: "Amaryllis", scientific_name: "Hippeastrum", water_schedule: "", fertilizer_schedule: "", info: "
Temperature:	The amaryllis within the growing period (winter - spring) prefers temperatures of 70 - 75F°f (21 - 24°c) and from September - November (or early December) 55°f (13°c). After the plant as flowered the temperature can be kept at around 70 - 75F°f (21 - 24°c) which will keep the flower healthier longer.
Light:	Bright light without too much direct sunlight is preferable.
Watering:	During the growing and flowering period, water when the top inch of the soil becomes dry. Once the leaves are cut away you can stop watering for about 8 – 10 weeks (dormant period) or water sparingly until new growth appears. When new leaves appear water frequently again when the top inch of soil becomes dry. Overwatering may cause the bulb to rot.
Soil:	You can use equal part perlite and peat or two parts loam soil and one part perlite. Your local garden store will offer other suitable options as well.
Re-Potting:	Your hippeastrum can be re-potted if the bulb seems to have outgrown the pot or every 2 years just before the dormant growing period (Nov - Dec). The pot size needs to be approximatively 2 inches wider each side of the bulb.
Fertilizer:	After the dormant period (Nov -Dec) begin feeding with a liquid fertilizer once every 2 weeks once you begin to see leaf shoots appearing. Continue until the leaves are cut down ready for the dormant period (Sept - Nov).
Humidity:	Normal room humidity is fine.
Propagation:	These can be propagated by seed (takes up to 5 years to mature and flower) or bulb offsets. Propagating with offsets takes about half the time to produce a mature plant that flowers compared to planting seeds (about 3 years).", image_url: "https://www.houseplantsexpert.com/image-files/amaryllis-red-white-flowers.jpg", category: "Flowering")

Plant.create(name: "African Violet", scientific_name: "Saintpaulia", water_schedule: "", fertilizer_schedule: "", info: "
Temperature:	Room temperatures of around 65°f / 16°c --- 75°f / 24°c are ideal. Try not to allow temperatures to decrease lower than 60°f / 15.5°c and it's advised to avoid cold drafts or abrupt temperature changes.
Light:	The African violet thrives in bright light, although too much direct sunlight will cause leaf problems (edges turn yellow, patches, or develop holes). I have grown mine, at best - close to east facing windows, but many other people grow them close to the south facing side. Growers will use artificial lighting to encourage blooms during winter time, using fluorescent lighting tubes. However, many of us do not want to use lighting and have the expense when we are happy enough to see the spring and summer blooms.
Watering:	A big mistake is to over water these or even water them with very cold water. Very cold water prevents growth, causes leaf spots and may cause a change in color. It's best to water them once the soil becomes slightly dry to the touch and water from the top or bottom. Any excess water at the bottom of a pot tray should be removed.
Soil:	A fast draining soil mix is best to use. I actually use the African V soil mix with 1 part vermiculite because it's cheap enough and easy to find in many stores.
Fertilizer:	Fertilize every couple of weeks with a balanced fertilizer that's urea-free. Or even better, a solution specifically for A.violets.
Re-Potting:	Re-pot when needed (room temperature not below 70°F./21°C). I would always do this at least once every year, or even twice a year. There is no need to increase the pot size, unless it becomes pot bound or has grown larger.
Air Humidity:	These need high humidity and plenty of gentle misting (with luke warm water, not in direct sunlight and only the leaves) for healthy growth and to flower well. You can use a humidity tray to support the correct levels that needs to have small pebbles or a layer of gravel at the bottom with water added below the surface.
Propagation:	A.voilets are propagated by leaf cuttings (Chimera AVs only by suckers), placed into a potting mix.
Grooming and pruning:	It's wise to remove dying leaves, flowers and the stems as soon as possible to encourage new growth. Remove new side shoots (suckers) as soon as they begin to grow as well. Removing crowns is to be done very carefully.", image_url: "https://www.houseplantsexpert.com/assets/images/av-pink-blue-1.jpg", category: "Flowering")

Plant.create(name: "Angel Wing Begonia", scientific_name: "Begonia Coccinea", water_schedule: "", fertilizer_schedule: "", info: "Temperature:	Average room temperatures of 55 - 75°F (13 - 24°C) are best suited for Begonias...and no less than 55°F.
Light:	This plant is not in favor of direct sun. This is because the leaves are sensitive to getting scorched. In their natural habitat most Begonias grow under cover. Bright light is best and during the winter some morning or late afternoon sun is fine.
Watering:	From spring - fall you will need to water this plant often, especially while it's in bloom. Keep the soil moist to the touch slightly, but do not overwater. During winter cut down watering and allow the top soil to become dry to the touch before watering again.
Soil:	African Violet ready made potting soil works well. Otherwise use a rich soilless well draining potting mix.
Fertilizer:	From spring - fall feed the plant while the soil is damp every 2 weeks. Use a high potassium diluted feed of 5-10-5. This seems to work well in keeping the leaves and flowers looking healthy.
Repotting:	While the plant is young I would repot every year in a pot slightly bigger. Once it matures every 2 years. Clay pots work well because they tend to release moisture easier, preventing root problems from stagnant water. An added benefit of using a clay pot is it will keep the plant more sturdy once it matures in height and prevent it from toppling over.
Humidity:	This plant enjoys a good amount of humidity. You can mist around the plant area, but I advise you not to water the leaves in case it causes spots or patches on them.
Propagation:	You may take take a few inches (4 - 6in) or more of stem cuttings with or without a leaf attached and without flowers. You want a node or more on the stem where a new flower will begin to grow. The stem cutting can be placed in water or in perlite (use a rooting hormone with perlite) until growth appears then it can be potted in soil. I prefer to stick with placing in water to see the roots form. These can also be grown from seed that is much more difficult for the average grower.
Pruning:	To keep your Begonia well formed and within the size you can manage indoors, prune back stems and pinch out stem tips that are growing too tall. Pruning will encourage new growth making the plant look much rounder and healthier.", image_url: "https://www.houseplantsexpert.com/assets/images/angel_wing_begonia.jpg", category: "Flowering")

Plant.create(name: "Barberton Daisy", scientific_name: "Gebera Jamesonii", water_schedule: "", fertilizer_schedule: "", info: "
Temperature:	Average temperatures of 55 - 75°F (13 - 24°C) are suitable.
Light:	A lover of direct sunlight and bright windowsills. Place close to a south, east or west facing window to provide enough sunlight.
Watering:	It's best to keep the soil moist at all times. Once the soil becomes slightly dry to the touch provide water straight away or the plant will begin to wilt very quickly.
Soil:	A peat based potting mix with 2 parts peat and 1 part perlite is suggested.
Fertilizer:	While flowering, feed with a balanced liquid fertilizer every 2 weeks.
Humidity:	Gerbera's quite like above average humidity levels, although average is absolutely fine.
Propagation:	These are mostly propagated with seeds although the parent plant can also be divided or root cuttings can be used.", image_url: "https://www.houseplantsexpert.com/assets/images/gerbera_jamesonii_1.jpg", category: "Flowering")

Plant.create(name: "Spider Lily", scientific_name: "Hymenocallis littoralis", water_schedule: "", fertilizer_schedule: "", info: "Temperature:	The Beach Spider Lily is capable of withstanding temperatures that drop into the 40ºF (4°C) range, and as high as 90ºF (32ºC). They must be protected against frosts by all means, or the plant will die back to the bulb stage.
Light:	This plant requires partial shade to full sun. Make certain it can get enough light from the pot location.
Watering:	Hymenocallis littoralis demands wet conditions all year long. The bulbs can be started in nothing except water, but need to be moved to soil once they begin to sprout. Soil should be kept moist, but never soggy. Do not allow standing water in the saucer underneath.
Soil:	These plants prefer a standard potting soil mixed with bark or pumice at a 1:1 ratio. The pH of the soil chosen needs to be between 5.0 and 7.5 for the continued health of the plant.
Fertilizer:	You may fertilize your plant once every two weeks with a diluted balanced fertilizer. Seaweed based fertilizers have been reported to produce the best results.
Re-Potting:	Every two years, this plant requires re-potting and an infusion of new soil. Move the plant to a size larger pot, and mix in new soil to fill the gaps. This should be done when the plant is not flowering.
Air Humidity:	This plant is happy with normal air humidity, as long as its soil is properly moist. If the soil has been allowed to dry out, the leaves and flowers may be misted with a spray bottle to combat dehydration effects.
Propagation:	This plant is propagated either by seed or by dividing rhizomes. Maturity from seed takes several years. It is easier to break off a piece of the bulb and propagate from it.", image_url: "https://www.houseplantsexpert.com/assets/images/beach_spider_lily_img.jpg", category: "Flowering")

Plant.create(name: "Belladonna Lily", scientific_name: "Amaryllis belladonna", water_schedule: "", fertilizer_schedule: "", info: "
Temperature:	Temperatures from 65 - 75F°f (18 - 24°c) are best suited.
Light:	Bright and direct sunlight is advisable. To stand any chance of getting the belladonna lily to flower it's best to have the plant near a south-facing window, where it can get the most hours of sunshine.
Watering:	Keep the soil moist (not soaked) during the growing and flowering period. During the rest period after the leaves have died down, do not water until the stalk appears and then begin watering as normal.
Soil:	You can use equal part perlite and peat or two parts loam soil and one part perlite. Your local garden center may also be able to offer other suitable options. Make sure the bulb is planted within a large plant pot.
Re-Potting:	Re-pot in a fairly large pot that gives the plant plenty of room for it's roots. Once every 2 -3 years should be fine.
Fertilizer:	Once the leaves appear you can fertilize with a diluted liquid fertilizer once a month. Do not feed during the rest period and begin again once the stalk appears. Feeding will help belladonna lily plants to flower, however, it's not necessary to do so and it's much better to give less or none at all - than too much.
Humidity:	Normal room humidity is fine.
Propagation:	These can be propagated by seed, bulb offsets or rhizome's.", image_url: "https://www.houseplantsexpert.com/image-files/amaryllis-belladonna.jpg", category: "Flowering")

Plant.create(name: "Bird of Paradise", scientific_name: "Strelitzia Reginae", water_schedule: "", fertilizer_schedule: "", info: "
Temperature:	The Bird of Paradise requires moderate temperatures year-round. They can tolerate temperatures as low as 55 ºF (13 ºC), but prefer to remain in the 70-90 ºF (21-32 ºC) range. Above 70 ºF (21 ºC), care instructions do change slightly.
Light:	This plant demands bright, yet indirect, sunlight year-round. Too much sunlight will injure the flowers. Above 70 ºF (21 ºC), this plant should be relocated to a partial shade environment in order to avoid sunburn on the flowers.
Watering:	During the summer months, the soil should be kept moist through regular watering. Throughout the fall and winter, permit the soil to almost dry out before watering. Never permit water to stand in the saucer underneath the plant.
Soil:	Strelitzia reginae does well in almost any type of soil. A standard potting soil will suffice for this plant's continued health.
Fertilizer:	Offer this plant a balanced fertilizer every two weeks throughout the spring and summer. During the fall and winter months fertilization to once every month.
Re-Potting:	Check the roots of this plant in the late winter. If the roots appear to be cramped in the current container, have someone assist you in moving it to a size larger pot. Be careful not to injure the spathe during the transplant process. Also, re-pot young plants which are growing early spring.
Humidity:	This plant prefers normal air humidity inside the home. During the winter months, you can mist the leaves of the plants to simulate rainfall, which will also improve humidity during the months that artificial heating is used.
Propagation:	The Strelitzia can be propagated from seeds or by division. The seeds are woody, brown and small, with tufts of orange on them. When propagating from seed, it will take the newly formed plant up to three years to begin blooming. When propagated by division, the process interrupts the growth cycle of the parent plant, resulting in a year without blooms.", image_url:"https://www.houseplantsexpert.com/assets/images/bird_of_paradise_plant_1.jpg", category: "Flowering")

Plant.create(name: "Blushing bromeliad", scientific_name: "Neoregelia carolinae", water_schedule: "", fertilizer_schedule: "", info: "Temperature:	Average to just above average temperatures of 65 - 80ºF (18 - 27ºC) are best suited. Avoid lower than 55ºF (13ºC).
Light:	A lover of bright light. A combination of some sun and shade provided throughout the day is advised or filtered sun.
Watering:	Fill the center vase with water - using distilled or rain-sourced water and change it every four to six weeks. The soil needs to be kept slightly moist but not soaked.
Soil:	A well draining and loose soil mixture is suitable. 1 part peat, 1 part bark and 1 part coarse sand or perlite is one mix which can be used.
Fertilizer:	This bromeliad does not need a lot of feeding. Once a month you can add a diluted liquid fertilizer (half the recommended strength on the instructions) to your misting bottle. Over feeding can cause leaf color loss.
Re-Potting:	You will only need to re-pot if the container used is no longer large enough. It's worth renewing the soil once a year, but if the soil mix has nutrients added to it - do not feed for the next month or two.
Humidity:	Providing average to above average humidity is advisable. To improve levels during summer or when artificial heating is used, you can mist the leaves, or provide a humidity tray for the plant and it's container to sit on. If you notice the leaves turning brown and dry this could be caused by dry air (lack of humidity).
Propagation:	Once the plant has flowered the mother plant will begin to die and produce pups - rather than grow it's leaves any further. These offsets are removed and used to create new plants by cutting them off as close to the main plant as possible, usually when they begin to grow roots or they're about a third of the size of the mother plant.", image_url:"https://www.houseplantsexpert.com/image-files/blushing_bromeliad1.jpg", category: "Flowering")

Plant.create(name: "Busy Lizzie", scientific_name: "Impatiens Walleriana", water_schedule: "", fertilizer_schedule: "", info: "Temperature:	Average room temperatures from 65°F/18.3°C - 75°F/23.8°C (not below 60°F/15.5°C).
Light:	Bright light is key to these blooming and during winter. Direct sun light is be to avoided during the summer.
Watering:	Keep the soil moist at all times but not soaking wet. During the growing season you will notice they drink a lot.
Soil:	A well draining potting soil mix will suffice.
Fertilizer:	Impatiens walleriana's grow well when fed with a balanced liquid fertilizer during spring and summer. I would say feeding once every 4 weeks is about right.
Re-Potting:	Re-pot during spring if the plant has become pot bound, but keep in mind the patient lucy likes plenty of roots in it's pot. When re-potting use a pot slightly bigger than the last one the plant resided in - with plenty of drainage holes.
Humidity:	Most indoor humidly levels are fine for this plant.
Propagation:	Stem cuttings (3 -5 inches) can be taken at any time of the year and re-potted to produce new busy lizzies. These can also be grown by seed which are sown during spring.
Pruning:	Trim back stems during spring to make the plant foliage look even, which should bring forth a much better fuller looking appearance during the growing season. Also remove fading flowers.", image_url:"https://www.houseplantsexpert.com/image-files/impatiens-walleriana-lilac.jpg", category: "Flowering")

Plant.create(name: "Calla lily", scientific_name: "Zantedeschia aethiopica", water_schedule: "", fertilizer_schedule: "", info: "Temperature:	These flowers can be rather picky about their temperatures. For ideal growing conditions expose the bulbs to days no hotter than 65°F and no colder than 55°F. The above ground plant can tolerate temperatures as high as 75°F. If your home is hot, use mulch to keep the bulb cooler in its pot.
Light:	This plant requires plenty of bright sunlight during non-peak hours of the day. Provide it with a sunny window facing east or west for best results.
Watering:	Zantedeschia aethiopica is a water loving plant. It grows best on the edges of ponds and in the mud. Because of this, your indoor lily will prefer moist conditions. Keep the soil always moist, but never allow water to sit in the container. Too much water will cause the bulb to rot.
Soil:	Standard potting soil is a good mixture for this plant. Avoid potting soils with an unbalanced pH or too much fertilizer mixed in.
Re-Potting:	This plant takes to re-potting well. Simply dig the plant out of the soil, including the entire bulb. Replant the bulb with the shoots pointing up at least three inches deep in the soil. Cover, and water once. Wait until new growth is evident before watering again.
Fertilizer:	The Calla Lily normally doesn't need fertilizer. If you desire better growth, use a fertilizer with no ammonium in it. Use this in a mixture of 1 part fertilizer to 1 gallon of water, and fertilize once every two weeks for a single season only. Continued fertilization for long periods of time will harm the plant.
Humidity:	Normal room humidity is acceptable for this plant, as long as the soil is kept moist. This is especially true during winter.
Propagation:	If the Calla Lily is fertilized, small black berries will form. These can be dried out and planted in three inches of potting soil. This will form new bulbs. Otherwise, you can dig up the rhizome and break off a section of it. Permit this to dry for two days, then plant with the non-smooth side up and water according to re-potting instructions.", image_url:"https://www.houseplantsexpert.com/assets/images/calla-lily-flower.jpg", category: "Flowering")

Plant.create(name: "Aluminum Plant", scientific_name: "Pilea Cadierei", water_schedule: "", fertilizer_schedule: "", info: "Temperature:	Pilea cadierei requires a year-round temperature between 60-75 ºF (15-23 ºC). It can tolerate short periods of time outside of this temperature range, but continued exposure will kill the plant.
Light:	This plant requires at least four hours of indirect, but bright, sunlight a day. Do not permit this plant to be exposed to overly bright or direct sunlight. Too much sun will burn the leaves and cause the green parts to turn brown.
Watering:	The Aluminum plant needs to be watered differently during different times of the year. During spring and summer, the top quarter inch of the soil should be kept moist. During fall and winter, allow the top quarter inch of soil to dry out before watering again. Do not permit water to stand in the saucer underneath the plant.
Soil:	This plant prefers a sandy soil mixture to live in. Combine one part clean sand (or perlite) with two parts peat to provide the required soil content for continued health.
Re-Potting:	Check the root density of Pilea cadierei every spring. If the roots are becoming overly dense, transplant the plant to a size larger pot. If you do not, the root system will break the container in an attempt to find more room to grow.
Humidity:	Normal air humidity will please this plant. If your home is overly dry during the winter, mist the leaves every other day with plain water.
Propagation:	This plant is propagated through cuttings. Take the cuttings in the early spring. Allow them to rest in a water source for one week, or until roots form. Then transplant to their own container of sandy soil mixture.", image_url:"https://www.houseplantsexpert.com/assets/images/pilea-cadierei-1.jpg", category: "Foliage")

Plant.create(name: "Areca Palm", scientific_name: "Chrysalidocarpus", water_schedule: "", fertilizer_schedule: "", info: "Temperature:	Average room temperatures of 65°F (16°C) --- 75°F (24°C) are suitable and no lower than 55°F (12.7°C). Sudden cold temperature drops and cold drafts can cause the leaves to display brown spots.
Light:	A fairly bright room without direct sunlight is advised. Not enough light will slow growth and too much sun can scorch leaves.
Watering:	Allow the top soil to become dry between watering and do not overwater. Overwatering is the quickest way to kill an areca palm, especially if the soil does not drain too well.
Soil:	To prevent roots from becoming water logged use a well draining aerated potting soil mix. A mixture of 1 part peat, 1 part pine bark and 1 part coarse sand is one possible good mix.
Fertilizer:	During spring and summer feed with a palm fertilizer or just a standard diluted feed. After re-potting with new potting mix do not use fertilizer for 2 months.
Re-Potting:	When re-potting - take care not to disturb the plant too much and only sit it as deep as it was previously in the soil (see marks on the cane from the soil to measure the previous level). This plant prefers being pot bound to a certain degree, so re-pot every three years.
Humidity:	Normal room humidity is usually fine; however, dry air turns leaf tips brown (this is common).
Propagation:	Propagation is done with seeds, but it's time consuming and quite difficult. You'll need to be able to keep temperatures at around 80°F (26°C) and provide above average humidity conditions. Using a heated propagator is best used to maintain the correct temperate and humidity levels.", image_url:"https://www.houseplantsexpert.com/assets/images/areca_palm_1.jpg", category: "Foliage")

Plant.create(name: "Arrowhead Plant", scientific_name: "Syngonium Podophyllum", water_schedule: "", fertilizer_schedule: "", info: "Temperature:	Temperatures of at least 60-85 ºF (15-29 ºC) need to be maintained year round. This species may cope with 50 ºF (10 ºC). Anything lower can kill off your plant.
Light:	Provide bright light without direct sunlight to prevent the leaves from getting scorched. Set back a few feet from a window that receives sun would be a nice spot. If you notice more growth on one side then turn the pot because that side is likely to be receiving more light (this will even growth out).
Watering:	When the top soil becomes dry to the to the touch slightly - water thoroughly. Reduce watering during winter to prevent plant problems.
Soil:	Any decent peat based soil potting mix will suffice.
Re-Potting:	Repot once every two years. After it has reached the growth you want - keep the same size pot and just make a new soil change every two years.
Fertilizer:	During spring - summer provide the plant with a diluted liquid feed once every two weeks. After summer stop feeding because the plant will no longer produce new growth to nourish.
Humidity:	In its natural habitat the Arrowhead plant receives plenty of humidity, however, in temperate regions most homes are suitable. Try to avoid dry air from heating systems (place water in containers to improve within the room or let air in through the windows - not too cold though). Misting the leaves is a good approach to improving humidity.
Propagation:	Between spring and summer you can take a 4in stem tip cutting with only one or two leaves (remove others). If a tip has new growth use that - it will propagate easier. Dip the cut into rooting hormone then plant in slightly moist potting soil. Water when the soil becomes dry then once new growth appears treat the plant the same as the parent. This plant can begin growing well when placed in water to begin rooting then pot it up.
Pruning:	Pruning during summer will encourage new growth and make the plant more bushy in appearance. To prevent the stems from climbing and growing too long pinch them at the tip of each stem that is now tall enough. You can also remove older stems. The stems removed can be propagated.", image_url:"https://www.houseplantsexpert.com/assets/images/syngonium_podophyllum.jpg", category: "Foliage")

Plant.create(name: "Bird's Nest Fern", scientific_name: "Asplenium Nidus", water_schedule: "", fertilizer_schedule: "", info: "Temperature:	Room temperatures between 65-75ºF (18-24ºC) are ideal, and no lower than 55ºF (13ºC).
Light:	Most books and guides will agree that bright light without direct sunlight should be provided. However, providing some direct sunlight is great for the Bird's nest fern to grow well, but you need to only provide some morning or a small amount of pre-sunset. The fronds can become pale or have scorch marks on them if the sun is too hot. During the winter the sun is much less harmful to the plant.
Watering:	This is a species that loves it's soil to remain moist at all times, but not soggy. Water around the edge of the center rosette to avoid the water becoming stagnant in the center, which may cause rot.
Soil:	A peat based potting mix is required. 2 parts peat and 1 part perlite (maybe a little less) is one mixture that will be fine. A peat based mixture with organic material is also good.
Fertilizer:	From April - September feed the plant with a weak diluted fertilizer every 2 weeks to encourage new growth and healthy looking leaves.
Re-Potting:	The Asplenium nidus does not need a pot change very often because it's roots are very small. Once every 2 years is advised for a mature species and once a year while it's young. These do not generally have a problem with becoming root bound, but have more of an issue with staying stable in the pot - this is because the roots are small and they're usually attached to a tree making their own mount. Watch out to see if the plant is becoming unstable and move to a larger pot if it is.
Humidity:	Humidity may need to be improved if it becomes low and the plant is showing signs of being affected by dry air. You can improve the humidity by standing the plant in a humidity tray, a tray of peat moss or use an electronic humidifier.
Propagation:	These are propagated by spore sowing which is very difficult for the average indoor grower to carry out. Many ferns can be propagated by division, not this species though.", image_url:"https://www.houseplantsexpert.com/images/a.nidus.jpg", category: "Foliage")

Plant.create(name: "Boston Fern", scientific_name: "Nephrolepis Exaltata", water_schedule: "", fertilizer_schedule: "", info: "Temperature:	The ideal room temperatures for Boston ferns is between 60-75ºF (16-24ºC). No lower than 55ºF (13ºC). Avoid warm air from indoor heating and cold drafts.
Light:	In their natural habitat these ferns will be provided small amounts of sunshine under trees, shaded. The best light conditions to provide is indirect sunlight, although a small amount of sunlight (when it's not too hot) encourages growth. Filtered sunlight through net curtains works well. You may want to rotate the plant to encourage even growth of the fronds.
Watering:	Moist soil at all times is advisable, without the soil becoming soggy.
Soil:	Peat moss potting soil mixes are best suited with perlite added combined with all-purpose soil. The soil needs to be able to retain some water but also have the ability to drain fairly well. Too much peat moss then water can become clogged and too much perlite with all-purpose will drain too quickly.
Fertilizer:	A balanced fertilizer diluted given to the plant every 2 weeks should suffice. Feed from April - Sept and don't feed after re-potting and changing the soil for one month (enough nutrients will be available in the new soil).
Re-Potting:	Re-potting is done during spring once every 2 years while it's growing fast to a pot size bigger. Still change the top soil each spring even if a pot change is not required.
Humidity:	All ferns prefer fairly high humidity levels, however, the Boston fern is slightly more resilient and can tolerate lower levels. If you can....increase levels with a humidifier and not a humidity tray because your likely to keep the plant in a hanging basket or similar, so the plant cannot be placed in a tray.
Propagation:	These are propagated either by division or separating runners. The runners are small plantlets that grow from the mother plant that you will have to look out for and remove once they have grown enough to separate from the mother plant and survive independently. Dividing the plant into sections is the most popular propagation method carried out during spring. You can divide the fern into how many new plants you want by cutting though the root system for the section you require.", image_url:"https://www.houseplantsexpert.com/assets/images/boston_ferns_in_hanging_baskets_1.jpg", category: "Foliage")

Plant.create(name: "Broadleaf lady", scientific_name: "Rhapis excelsa", water_schedule: "", fertilizer_schedule: "", info: "Temperature:	It is almost impossible to upset the temperature of the Broadleaf Lady Palm. It will happily tolerate temperatures from 20-100°F (-6-37°C), and can survive short stays outside of this temperature zone.
Light:	This palm enjoys indirect sunlight. Full sunlight will injure the leaves.
Watering:	Rhapis excelsa demands soil that is constantly moist, but never soggy. Do not permit standing water to collect, as it will rot the root system.
Soil:	Although tolerant of many soil types, this plant's standing favorite is African Violet potting soil mix.
Fertilizer:	This plant rarely requires fertilizer. You may use a balanced 10-10-10 mixture, but it is very easy to over-fertilize and injure the plant.
Re-Potting:	This plant rarely requires fertilizer. You may use a balanced 10-10-10 mixture, but it is very easy to over-fertilize and injure the plant.
Humidity:	The Broadleaf Lady Palm is tolerant of any humidity offering. Misting regularly is advised during warmer months.
Propagation:	When propagating from seeds, this plant will require 7 years of care before it reaches house plant size. Propagation usually takes place from the rhizome root system. You may dig down and break off several stems from the existing root system at any time without fear of harming the plant.", image_url:"https://www.houseplantsexpert.com/image-files/broadleaf_lady_palm1.jpg", category: "Foliage")

Plant.create(name: "Canary Date Palm", scientific_name: "Phoenix Canariensis", water_schedule: "", fertilizer_schedule: "", info: "
Temperature:	Happily tolerate temperatures from 20-100°F (-6-37°C), and can survive short stays outside of this temperature zone.
Light:	The Canary date palm loves it's sunlight. Your best to provide it a combination of sunlight and shade, which makes an east or west facing window a good spot to place your plant.
Watering:	AVOID over-watering and don't allow the soil to lack good drainage. I would allow the soil to become slightly dry at the top and then water.
Soil:	A peat based potting mix with good drainage is best used. Two parts peat and one perlite or sand works fine. Fine pine bark works well within a mix too.
Fertilizer:	I always use a feed specifically for palms because they are very sensitive to being over fed and need the right balance of nutrients suitable for them. Keep in mind that your b
Re-Potting:	You only need to re-pot this palm when it has become pot bound. Every 2 years you can top dress the soil by removing the top few inches and replacing it, then every 4 years completely renew the soil and check the root systems size and health. Roots may need pruning.
Humidity:	Average room humidity is fine and mist leaves during summer.
Propagation:	Propagate from seed. Temperatures of approximately 80°F (27°C) are required - making propagation difficult for the average grower.", image_url:"https://www.houseplantsexpert.com/images/canary.jpg", category: "Foliage")

Plant.create(name: "Cast Iron Plant", scientific_name: "Aspidistra elatior", water_schedule: "", fertilizer_schedule: "", info: "Temperature:	Average warmth is fine of approximately 60-75°F (15-24°C) and no lower than 45°F (8°C). They will tolerate much lower temperatures.
Light:	A brightly lit room is good but not essential. They're fine with low levels of light, but it's best to keep them out of direct sunlight which will damage the leaves.
Watering:	Water once the top one inch of soil becomes dry. Water less during winter and do not over water. Over watering to the degree that the soil becomes soggy for a period of time - can cause the plant to die. The Aspidistra elatior is drought tolerant so if it misses being watered even for a month it will look unwell but be right back with you once care and water is given again.
Soil:	Most well draining potting mixes will suffice and good drainage holes at the bottom of the pot is advised.
Fertilizer:	During the main growing season (spring - summer) feed with a balanced liquid fertilizer which is diluted, once a month.
Re-Potting:	Re-pot only when needed (spring) or once every 2 - 3 years.
Humidity:	Average house humidity is advised but the cast iron plant can tolerate dry air conditions.
Propagation:	Propagate by division when its re-potting time.
Pruning:	Prune leaves at the stem (near to the soil as possible) when they are deteriorating. When you have too many stems and the plant becomes oversized the plant can be divided (roots and stems). Divisions can be re-potted to create new cast iron plants.", image_url:"https://www.houseplantsexpert.com/image-files/Aspidistra_Elatior.jpg", category: "Foliage")

Plant.create(name: "Chinese Evergreen", scientific_name: "A. commutatum", water_schedule: "", fertilizer_schedule: "", info: "
Temperature:	Temperatures between 65-80 ºF (18-27 ºC) are ideal. Lower than 60ºF (15ºC) is not healthy for this plant and can cause dark patches on the leaves. If the leaves begin to curl and the edges turn brown the temperature is probably too low or cold drafts may be affecting the plant.
Light:	The most common advice I have been given for the Aglaonema is the darker the leaves and stalks, the less light is needed. I would say to be safe a bright room with the plant sitting in a shaded spot is best. Avoid direct sunlight.
Watering:	Keep the soil moist at all times. Water less in the winter.
Soil:	A peat based potting soil mixed with part perlite or sand to improve drainage is ideal or any other well draining potting mix.
Fertilizer:	From spring until the and of summer they like to be fed with a diluted liquid fertilizer.
Re-Potting:	Re-pot once every two or three years during spring. They like to become slightly root bound - so don’t worry if they seem to showing some roots through the bottom of the pot.
Humidity:	Average to high room humidity is needed. Increasing the humidity levels of a room "especially if the room has artificial heating" will improve the plants growth and prevent leaves from becoming dry and shrilling up.
Propagation:	These are best propagated by dividing the root with a few stalks and leaves attached during spring and summer.
Insects:	Over the years mealy bug have proven to be attracted to this plant and cause problems. Red spider mite have also been known to cause problems.", image_url:"https://www.houseplantsexpert.com/image-files/aglaonema.png", category: "Foliage")

Plant.create(name: "Coral bead", scientific_name: "Nertera granadensis", water_schedule: "", fertilizer_schedule: "", info: "
Temperature:	Nertera granadensis prefers temperatures on the cooler side. The plant should remain at 55-65ºF (13-18ºC) all year round. Occasional temperature spikes as high as 80ºF (26ºC) and low as 40ºF (4ºC) are tolerated, but must be remedied within a week for the plant's health. Temperatures above 65ºF (18ºC) during flowering will result in no berries produced during that season.
Light:	This plant demands a source of light that is bright, yet indirect, in order to maintain its health.
Watering:	Requires different watering demands depending upon the time of year that you are in. During the spring and summer, this plant should be kept moist at all times. Soil should be watered whenever it begins to feel dry, but never kept soggy. During summer months, the plant should remain on a saucer of wet pebbles to offer the increased moisture demanded. In autumn and winter, the plant's soil should be permitted to dry almost completely before watering again.
Soil:	This plant possesses a shallow root system. As such, the pot does not need to be more than a few inches deep. One part potting mix to one part perlite or tree bark is the preferred soil choice.
Fertilizer:	A balanced fertilizer, diluted to one-half strength, should be applied to the plant in a misting fashion once a month throughout the year. Do not pour the fertilizer directly onto the soil, as it will sink beyond reach of the shallow root system.
Re-Potting:	When needed, the coral bead plant should be re-potted in the spring season only. It will remain confined within its available space happily for its entire life, so re-potting is only needed if you desire a larger plant.
Humidity:	During spring and summer months, this plant requires daily misting of the flowers and berries. In autumn and winter, occasional misting is needed on a weekly basis.
Propagation:	For Nertera granadensis, propagation is best achieved by division. In the spring, pull a clump of the plant away from the mother plant and pot it its own location. Seed and tip cuttings are other propagation methods, but require years to reach maturity.
Common Problems:	Plants that are too hot will refuse to produce berries, even after producing flowers. Exposure to excessive sunlight will cause the leaves to burn and the berries to shrivel.", image_url:"https://www.houseplantsexpert.com/assets/images/Nertera-Granadensis-1.jpg", category: "Foliage")

Plant.create(name: "Aloe Vera", scientific_name: "Aloe barbadensis", water_schedule: "", fertilizer_schedule: "", info: "
Temperature:	Temperatures averaging 70°F/21°C - 80°F/26°C are very good and not much below 50°F/10°C.
Light:	The A.Vera thrives on bright light conditions, but not direct sunlight. Heat is fine because they react similar to a cacti in hot conditions. Bright rather than light (direct), is the key.
Watering:	These are succulents which are mainly made up of water and retain a lot of water in it's foliage (for storage), similar to a cactus. The soil needs to be moist which is easy to check by placing a finger an inch deep into the soil to make sure it is not dry. It needs much less in the winter. .
Soil:	A pot mixture used for cactus will suffice or a soil mix that drains well and is well aerated.
Re-Potting:	Re-pot when the plant has outgrown it's pot. It's best to re-pot the offsets (small aloes - pups) in separate pots once they have grown enough.
Air Humidity:	Humidity is not a major concern for these, making the average room indoors sufficient.
Propagation:	Aloe offsets can be divided carefully and then re-potted. Pups will grow from the parent plant which are best removed when they are about 2 inches long, or when the main plant needs more room to grow. Leaf cuttings can also be taken and re-planted, although this method is not as successful. I would let cuttings dry out for at-least a few days before placing them in soil mix. Drying out allows time for the wound to heal and improve it's chance of growing.
Where they grow best:	As mentioned above these love bright conditions, making them a plant that will grow well on a shelf, windowsill or other area, without direct sunlight.", image_url:"https://www.houseplantsexpert.com/assets/images/aloe-foliage-1.jpg", category: "Succulent and Cacti")

Plant.create(name: "Unknown", scientific_name: "Argyroderma testiculare", water_schedule: "", fertilizer_schedule: "", info: "
Temperature:	Due to where the Argyroderma testiculare originated from it can comfortably handle temperatures of up to 85°F (30°C), however, it is not frost resistant and will need to be protected from cold weather (Min 50°F - 10°C) .
Light:	The Argyroderma testiculare thrives best in areas that are sunny but have partial shade. Some direct sun is great, so if possible, balance is best. Living stones are not happy in complete shade, it does not conform with their natural habitat at all.
Watering:	Due to its succulent nature, the plant is drought-tolerant and has average water needs. It is important that it is not over-watered. Watering during winter can almost cease. Overwatering is the worst thing you could do, especially if temperatures are cold. Water when the soil becomes dry to the touch.
Soil:	This is a plant that likes a loamy soil and therefore, a cactus potting mix is ideal. Should you want to mix your own soil it will require one part of course sand to two parts soil in order to encourage healthy drainage. Many growers will cover the top soil with gravel or small rocks which is fine to do and encourages drainage.
Re-Potting:	There will be a requirement to repot the plant every two to three years as it can outgrow the container. Containers do not have to be deep as the plant does have shallow roots. Using clay pots is beneficial because they are porous and remove water quicker, preventing waterlogged soil.
Air Humidity:	Providing the air humidity is average to dry, the plant will grow perfectly well. They're not high humidity lovers unlike many plants.
Propagation:	Grown from seed, during the winter sowing will have to be place in vented containers or an unheated greenhouse. Seeds can be sown indoors prior to the last frost and germinated in a damp paper towel. Another option is to separate by division if clumps have formed .
Fertilizer:	Fertilizing once a month is advised but once the flowering begins, stop. Begin feeding again once growth appears. A cactus diluted fertilizer is good to use, at about half the strength. It's debatable whether or not these type of plants even require feeding, so you could choose not to feed, but I would advise you to change the soil every two years (the new soil will provide nutrients).", image_url:"https://www.houseplantsexpert.com/assets/images/argyroderma_flowering_lithops.jpg", category: "Succulent and Cacti")

Plant.create(name: "Baby Rubber Plant", scientific_name: "Peperomia obtusifolia", water_schedule: "", fertilizer_schedule: "", info: "Watering:	The baby rubber plant is fairly easy to water. Allow the top soil to dry out completely and then water thoroughly. You do not want to over water this plant and allow the soil to become waterlogged....so it might be best to lean towards less rather than too much when you first start growing Peperomias, as less harm can be caused compared to overwatering.
    During winter water sparingly as the thick leaves will store water, so don't get too concerned about the soil being dry.
    Soil:	A peat based soil is best used that drains well. 2 parts peat and 1 part perlite or sand is a good mix. Other mixes will work well, but the main point is for the medium to drain well and be well aerated.
    Re-Potting:	You will not need to repot or pot up a size very often as this plant has a small root system. It's a good idea to change the soil or at least the top soil annually and if a young plant has out grown its current pot you may repot a size up during spring. Better to lean towards a smaller pot than a pot too large to prevent the soil becoming waterlogged. Shallow pots are a good option for Peperomias.
    Fertilizer:	During spring - while the plant is growing use a diluted liquid fertilizer once every 2 weeks, and once a month during summer. No feeding is required from autumn to spring
    Humidity:	This species does like a humid environment. During the warmer months you can mist the leaves and/or place the plant on a pebble tray with water at the bottom. Most homes should be fine with its natural humidity if the air is not dry.
    Propagation:	An easy method to propagate is to take a few centimeters of stem tip cuttings. Remove a tip (petiole) with about 5 - 8 cm of tip with one or two leaves on it. Plant the cutting in a very small pot with fresh potting mix that's moist and try to provide warm temperatures of about 20ºC (68ºF), and plenty of bright light (warmth and light is the key to success). You may want to use a rooting hormone on the cut being planted.
    The baby rubber plant can also propagate with leaf cuttings, although variegated types may lose the variegation. You may want to experiment and try a few leaves and stem tips to see what propagation method works best for you. I would allow leaves or stem tip cuttings a day to dry out until planted. Wait for new growth and be careful not to overwater the move a pot size up once plenty of growth has happened.
    Pruning:	If stems and leaves begin overgrowing you can pinch out the top of certain stems to stop growth, otherwise they begin to grow spindly and out of shape in appearance. To get them looking their best, try and grow and prune them to display a bushy appearance.", image_url:"https://www.houseplantsexpert.com/assets/images/american_baby_rubber_plant.jpg", category: "Succulent and Cacti")

Plant.create(name: "Bunny Ear Cactus", scientific_name: "Opuntia Microdasys", water_schedule: "", fertilizer_schedule: "", info: "Temperature:	This cactus enjoys temperatures ranging from 70-100°F (21-37°C), but demands cooler temperatures during the winter months. Starting in the late fall, this cactus should be kept between 50-65°F (10-18°C), and away from central heating vents. The cooler spell is demanded over the course of the entire winter, during which time the segments of cactus will turn a light gray color. Failure to provide these controlled winter conditions will result in plant death the following spring.
Light:	Demands full light growing for most of the year, except during the winter cycle. For the plant's health, light should be reduced to partial sun during this time.
Watering:	The Polka-dot Cactus is a desert species. It should be given water on a regular basis during its first season in a new pot. This will help it to create a strong root system. The soil should be kept moist, but not soggy. After the first season, more sporadic watering is required. During the winter cycle, the cactus should not be watered at all, with watering to resume in the early spring.
Soil:	Like most cacti, this specimen demands sandy soil-bases that drain easily. It is usually happy with the pre-packaged cactus soil found in common hardware stores. To increase drainage for a picky plant, mix in a 1:1 ratio of perlite or bark.
Fertilizer:	Monthly feeding of low nitrogen fertilizer. Fertilization should stop one month before the planned winter cycle for the plant's health.
Re-Potting:	Re-potting should take place in the summer, after the year's bloom has finished. Remember to water the plant regularly to promote the growth of a healthy root system during its first year in the new pot.
Humidity:	Prefers low humidity conditions. Consider running a dehumidifier in the room where the cactus lives to provide it with the most ideal conditions possible.
Propagation:	Any fully grown pad from this cactus may be broken off cleanly in the early summer and re-potted for propagation purposes. Cuttings work best when grouped in threes or more, and should be buried an inch deep in the soil. Remember to water regularly to promote the growth of a healthy root system in the first year after propagation.", image_url:"https://www.houseplantsexpert.com/image-files/bunny-ear-cactus-growing.jpg", category: "Succulent and Cacti")

Plant.create(name: "Century Plant", scientific_name: "Agave americana", water_schedule: "", fertilizer_schedule: "", info: "Temperature:	The plant thrives in warm temperatures during the summer although the winter months can prove troublesome should the temperature fall below 10°C. It handles changes in day and night time temperatures very well. Temperatures averaging 70°F/21°C - 80°F/26°C are very good and not much below 50°F/10°C.
Light:	While it can be kept in partial shade it does require full sunlight. This means that it will grow well on a sunny windowsill or outside soot that is south or east facing. During the winter months it is crucial that the plant receives as much light as possible.
Watering:	Like other succulents, the Agava americana does need more water during its growth period. Water enough to make the potting mixture moist but allow two thirds of the potting mixture to dry out before watering again. During the rest period the plant requires very little water and only enough to stop the potting mixture from drying out. In it's natural sub-tropical and semi-arid regions it spends a lot of time without water and survives well because the leaves are storage organs for water and nutrients.
Soil:	The Century plant does prefer a soil that drains very well. This does mean that the loam soil should be used that contains sand so that it remains moist but drains well. The soils should be PH Acid Neutral.
Fertilizer:	A liquid fertilizer will be fine to use every two weeks while the plant is actively growing. During the rest period the plant will not require fertilizing.
Re-Potting:	The plant should be re-potted each spring while it's growing, moving it in a pot that is one size larger. To enhance drainage a layer of broken crocks in the base of the pot will help drainage. Once the plant has reached the maximum convenient pot size it should be top-dressed during the spring months.
Air Humidity:	The plant will grow well in a room that consists of a normal humidity. Fresh air benefits this species. >
Propagation:	Offsets that can be found at the base of the plant can be used to propagate. Once the offset is around 8-10cm long it can be detached and put into a standard potting mixture. Ensure that it is well rooted and only give it enough water so that the potting mixture is slightly moist. They are also propagated with seeds.", image_url:"https://www.houseplantsexpert.com/assets/images/agave_americana.jpg", category: "Succulent and Cacti")

Plant.create(name: "Christmas Cactus", scientific_name: "Schlumbergera Bridgesii", water_schedule: "", fertilizer_schedule: "", info: "", image_url:"https://www.houseplantsexpert.com/image-files/christmas-cactus-with-red-flowers.jpg", category: "Succulent and Cacti")

Plant.create(name: "Christmas cheer", scientific_name: "Sedum rubrotinctum", water_schedule: "", fertilizer_schedule: "", info: "
Temperature:	It is more suited to hotter climates and this means that temperatures below freezing will damage the plants. Moving the plant indoors during cold snaps will help to maintain its growth and health, especially if placed on a windowsill that is western or southern facing. N No lower than 50 °F (10°F) - 55°F (12.7°C) is best and during summer between 65°F (18°C) - 75°F - (23.8°C+).
Light:	Some direct light is preferable for this plant. South facing windows are ideal or west, north facing will not encourage growth. It can handle cooler climates and hotter climates and because it can handle drought conditions it can be placed in areas that are exposed to long periods of sunlight.
Watering:	Even though the Sedum rubrotinctum has the ability to cope with dry conditions it will require extra water during the spring and summer months. However, it is important to give the plant time to dry out before watering it again.
Soil:	Due to its hardy nature, it has the ability to deal with a number of soil types although it does not do particularly well in soils that do not drain well. A cactus ready mix works well.
Re-Potting:	I would suggest a grower repot every two years unless the plant as outgrown the pot. This is best done during spring.
Air Humidity:	Normal room humidity is fine. Providing air circulation during the warmer months is advised (open doors or windows).
Propagation:	To achieve this, leaves that are situated on the stem will have to be removed and dried out. Once dry, they can be placed in moist soil, ensuring that the soil remains moist until the cutting begins to grow.
Fertilizer:	During the spring and summer months it should be fertilized once a month with a diluted liquid feed at maybe half the strength.", image_url:"https://www.houseplantsexpert.com/assets/images/sedum_rubrotinctum.jpg", category: "Succulent and Cacti")

Plant.create(name: "Coral Cactus", scientific_name: "Eurphorbia lactea crest", water_schedule: "", fertilizer_schedule: "", info: "
Temperature:	The Coral likes it's sunshine and warm conditions which help it to grow and maintain's it's health. A partially sunny spot and average temperatures of no lower than approximately 60°F (15°C) will suffice.
Light:	These do prefer good light conditions and sunlight, although it's best to provide them with partial sunlight and shade in high temperatures. This is the type of plant that grows lopsided if it only receives sunlight on one side, which is worth noting.
Watering:	Before watering the coral cactus check underneath the pot through the drainage holes to see if the roots are dry. If so then add some water. Do not water too often to prevent over watering, that can potentially kill it off.
Soil:	A cactus soil mix will be fine. The mix needs to be a type that is light and drains easily to prevent the roots from getting water logged.
Fertilizer:	Using fertiliser once each season is a good method, but not in the winter. A good succulent and cacti product bought will provide the correct instructions to follow.
Re-Potting:	Re-pot only when necessary (becomes pot bound, but that's unlikely). It may be safest to re-pot as soon as you get the Coral home in-case the mix, pot or both are not adequate.
Propagation:	These are propagated with cuttings taken in spring, which need to be dried out for a couple of weeks before potting (source; EwaterPlant Bangkok). Do remember that the sap from the Coral is poisonous, so take precautions (gloves - protective eye-wear).", image_url:"https://www.houseplantsexpert.com/image-files/coral-cactus-orig.jpg", category: "Succulent and Cacti")

Plant.create(name: "Donkey's and Burros Tall", scientific_name: "Sedum Morganianum", water_schedule: "", fertilizer_schedule: "", info: "Temperature:	Temperatures averaging 65°F/18°C - 80°F/26°C are very good and not much below 50°F/10°C. During winter it is fine if the temperature drops down and it can encourage them to actually bloom in the forthcoming spring season.
Light:	For this species to grow well you will need to at least provide a good amount of direct light. And, if you can sunshine, but not too much during the afternoon summer sun.
Watering:	During the growing season from April - September water the plant thoroughly and then water when the soil becomes dry to the touch. During winter cut down on the watering, which the plant may only need once a month. Remember it's a succulent and stores water in it leaves and stems...when you think it's lacking water it is not. Underwatering is much safer that overwatering and it's the No 1 killer for this plant.
Soil:	Potting mix that keeps the roots well aerated and drains well is required. To keep it simple I would pot up with a ready made cactus soil mix.
Re-Potting:	You will only need to repot this plant during spring when the existing pot has become to small for it and use a shallow pot (the roots do not grow very long).
Air Humidity:	Normal room humidity seems to work fine. Try and provide plenty of air circulation (open windows, doors, etc.) during summer.
Propagation:	Two methods are suitable for propagation. Leaf cuttings can be taken and placed in soil after the leaves have been left to dry for about 2 - 3 days. A couple of inches of stem can also be taken at the tip of the plant stems. After placing the stem tips in soil (only keep 2 or 3 leaves and remove others) and watering the soil once. I would not water again until I could see some sign of growth in case overwatering kills it.", image_url:"https://www.houseplantsexpert.com/assets/images/sedum_morganianum_plant_on_shelf.jpg", category: "Succulent and Cacti")

Plant.create(name: "Easter Cactus", scientific_name: "Hatiora Gaertneri", water_schedule: "", fertilizer_schedule: "", info: "
Temperature:	Temperature: The tropical Hatiora gaertneri prefers spring, summer, and fall temperatures around 75-80°F (24-27°C). Winter temperatures should be between 45-6°5F (7-18°C) only.
Light:	This tropical cacti likes bright partial light only. It should never be exposed to full sunlight or midday sunlight.
Watering:	Soil should be kept constantly moist, but never soggy. Do not allow water to sit in the dish underneath.
Soil:	Due to its natural growing environment being on rocks or trees, this cactus requires rough soil to grow well. A 1:1 mixture of potting soil to pumice, tree bark, or perlite is required. Pumice is preferred.
Fertilizer:	The Easter cactus prefers fertilization every 14 days. Use a balanced 10-10-10 fertilizer, and dilute to half strength. Do not fertilize during resting period.
Re-Potting:	Never re-pot during the bloom or following resting period. Re-pot by removing only the loose soil around the roots. Transfer immediately to a size larger pot and pack in with appropriate soil.
Humidity:	Hatiora gaertneri requires a humid environment to survive. The plant should be misted with a sprayer daily, even during the rest period, to simulate the needed humidity.
Propagation:	Any segment at least 3 inches long can be used for propagation. Allow the cutting to harden for at least 48 hours. Plant the small end of the segment in shallow, moist perlite. Rooting occurs between 3-4 weeks.", image_url:"https://www.houseplantsexpert.com/image-files/easter-cactus-buds.jpg", category: "Succulent and Cacti")


